<a href="https://colab.research.google.com/github/jtj7387/AI_2020_spring/blob/master/02_MathPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

math primier for AI

In [1]:
import numpy as np

Math multiplication

In [2]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [3]:
a.shape

(2, 3)

In [4]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [5]:
b.shape

(3, 1)

In [6]:
c = np.matmul(a, b)
print(c)

[[4]
 [2]]


In [7]:
c.shape

(2, 1)

In [8]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


In [9]:
d.shape

(2, 1)